### ISSUE TITLE
No need watch in node_modules, failing with ENOSPC

### ISSUE THREAD

**Issue by imShara** [csstime/csstime-gulp-tasks#36]
_From @imShara on December 22, 2016 0:57_

```
<...>

[2016-12-22T00:51:07.442Z] [FATAL] [catberry:30047] – Error: watch /home/user/foo/bar/node_modules/orchestrator/node_modules/end-of-stream ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1305:19)
    at Object.fs.watch (fs.js:1330:11)
    at createFsWatchInstance (/home/user/foo/bar/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/user/foo/bar/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/user/foo/bar/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/user/foo/bar/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/user/foo/bar/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/user/foo/bar/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:111:15)

[2016-12-22T00:51:07.442Z] [FATAL] [catberry:30047] – Error: watch /home/user/foo/bar/node_modules/orchestrator/node_modules/once ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1305:19)
    at Object.fs.watch (fs.js:1330:11)
    at createFsWatchInstance (/home/user/foo/bar/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/user/foo/bar/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/user/foo/bar/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/user/foo/bar/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/user/foo/bar/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/user/foo/bar/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:111:15)

<...>
```
Dirty fix - increase `max_user_watches` per user
```bash
echo fs.inotify.max_user_watches=500000 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

_Copied from original issue: catberry/catberry-assets#18_

**Comment by imShara** [comment]
_From @pragmader on December 22, 2016 9:49_

Thanks for pointing this out.
What makes you think it's catberry-assets related?

**Comment by imShara** [comment]
> What makes you think it's catberry-assets related?

Sorry, that's not about `catberry-assets`. The [problem is](https://github.com/csstime/csstime-gulp-tasks/blob/develop/gulp-tasks/csstime-mode-watch.js) in dependency — `csstime`.

**Comment by jughosta** [comment]
@imShara Hi! What configuration do you have for `componentsGlob` in catberry config? It is `['catberry_components/**/cat-component.json','node_modules/*/cat-component.json'` by [default](https://github.com/catberry/catberry/blob/8.6.0/docs/index.md#config).

**Comment by imShara** [comment]
> Hi! What configuration do you have for componentsGlob in catberry config?
I have no custom `componentsGlob` parameter in config, it's default.

I think that problem appears because i never used so many node modules in my projects that csstime has. It pulls _anything_ that you can use, e.g less and sass and postcss even if you use one or nor of them.

Clean Catberry node_modules dir: 7696 files, 18,5MB
With catberry-assets module: 19692 files, 71,0MB

Default `max_user_watches` value is 8192

Can you post output  of `sudo sysctl -p` if on linux?

**Comment by rdner** [comment]
@imShara let's clarify again.

**Neither catberry, nor csstime watch `node_modules` directory on purpose.**

Catberry watches only files included to the browser bundle or possible paths where components could appear which includes `node_modules/*/cat-component.json` glob by default. I assume [chokidar](https://www.npmjs.com/package/chokidar) is not smart enough to not watch every possible directory inside `node_modules` and it became a problem when NPM 3 started using the flat structure of dependencies, now all the dependencies are there on the first level of the directory.

If you didn't use `require` for a huge graph of dependencies in your client-side code the only probable thing would be the `componentsGlob` parameter which @JuliaRechkunova asked about.

Set `componentsGlob` to `['catberry_components/**/cat-component.json']` in your `build.js` and `server.js` as it's described [here](https://github.com/catberry/catberry/blob/8.6.0/docs/index.md#config).

**Comment by pragmader** [comment]
@imShara could you create a repo with a test project that reproduces the issue?

**Comment by jughosta** [comment]
@imShara Hi! Have you tried to update `componentsGlob`?
